/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoempresalvp.gui;

/**
 *
 * @author Administrador
 */
public class VentanaGUI extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGUI
     */
    public VentanaGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGUI = new javax.swing.JPanel();
        PanelPestañasPrincipal = new javax.swing.JTabbedPane();
        jPinicio = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        bImprimir = new javax.swing.JPanel();
        jPinsertarCli = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ctCliente = new javax.swing.JTextField();
        ctDescripcion = new javax.swing.JTextField();
        ctNombre = new javax.swing.JTextField();
        ctDomicilio = new javax.swing.JTextField();
        ctLocalidad = new javax.swing.JTextField();
        ctCp = new javax.swing.JTextField();
        ctProvincia = new javax.swing.JTextField();
        ctNif = new javax.swing.JTextField();
        ctTlfCli = new javax.swing.JTextField();
        ctCuenta = new javax.swing.JTextField();
        ctContacto = new javax.swing.JTextField();
        ctTlfContacto = new javax.swing.JTextField();
        aNotas = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        ctDomiciliado = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        ctRefBan = new javax.swing.JTextField();
        bNuevo = new javax.swing.JButton();
        bModificar = new javax.swing.JButton();
        bFormularioCon = new javax.swing.JButton();
        bImprime = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        cbNombre = new javax.swing.JCheckBox();
        cbDescripcion = new javax.swing.JCheckBox();
        cbNif = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jPcontratos = new javax.swing.JPanel();
        PanelPesContratos = new javax.swing.JTabbedPane();
        jPgestion = new javax.swing.JPanel();
        jPestudios = new javax.swing.JPanel();
        jPfacMens = new javax.swing.JPanel();
        jPfacExtra = new javax.swing.JPanel();
        jPempleados = new javax.swing.JPanel();
        jPotros = new javax.swing.JPanel();
        PanelPesOtros = new javax.swing.JTabbedPane();
        jPhistorico = new javax.swing.JPanel();
        jPhojasBan = new javax.swing.JPanel();
        jPrecibos = new javax.swing.JPanel();
        jPetiquetas = new javax.swing.JPanel();
        jPprograma = new javax.swing.JPanel();
        PanelPesPrograma = new javax.swing.JTabbedPane();
        jPcerrar = new javax.swing.JPanel();
        jPcontraseña = new javax.swing.JPanel();
        jPipc = new javax.swing.JPanel();
        jPnumFac = new javax.swing.JPanel();
        jPcopiasSeg = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPinicioLayout = new javax.swing.GroupLayout(jPinicio);
        jPinicio.setLayout(jPinicioLayout);
        jPinicioLayout.setHorizontalGroup(
            jPinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPinicioLayout.createSequentialGroup()
                .addComponent(jLabelImagen)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPinicioLayout.setVerticalGroup(
            jPinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelPestañasPrincipal.addTab("INICIO", jPinicio);

        bImprimir.setBackground(new java.awt.Color(102, 102, 255));

        jPinsertarCli.setBackground(new java.awt.Color(204, 204, 255));
        jPinsertarCli.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Cliente");
        jPinsertarCli.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 33, -1, -1));

        jLabel2.setText("Nombre");
        jPinsertarCli.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 71, -1, -1));

        jLabel3.setText("Domicilio");
        jPinsertarCli.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 109, -1, -1));

        jLabel4.setText("Localidad");
        jPinsertarCli.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 147, -1, -1));

        jLabel5.setText("CP");
        jPinsertarCli.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 185, -1, -1));

        jLabel6.setText("Contacto");
        jPinsertarCli.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 415, -1, -1));

        jLabel7.setText("Tlf");
        jPinsertarCli.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 453, -1, -1));

        jLabel8.setText("Notas");
        jPinsertarCli.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 495, -1, -1));

        jLabel9.setText("NIF/CIF");
        jPinsertarCli.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 223, -1, -1));

        jLabel10.setText("Tlf");
        jPinsertarCli.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 261, -1, -1));

        jLabel11.setText("Descripción");
        jPinsertarCli.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 33, -1, -1));

        jLabel12.setText("Provincia");
        jPinsertarCli.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 185, -1, -1));

        jLabel13.setText("Número de cuenta");
        jPinsertarCli.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 296, -1, -1));
        jPinsertarCli.add(ctCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 70, -1));
        jPinsertarCli.add(ctDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 168, -1));
        jPinsertarCli.add(ctNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 68, 282, -1));
        jPinsertarCli.add(ctDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 106, 282, -1));
        jPinsertarCli.add(ctLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 144, 129, -1));
        jPinsertarCli.add(ctCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 182, 70, -1));
        jPinsertarCli.add(ctProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 182, 97, -1));
        jPinsertarCli.add(ctNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 220, 236, -1));
        jPinsertarCli.add(ctTlfCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 258, 148, -1));
        jPinsertarCli.add(ctCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 316, 372, -1));
        jPinsertarCli.add(ctContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 412, 181, -1));
        jPinsertarCli.add(ctTlfContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 450, 151, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        aNotas.setViewportView(jTextArea1);

        jPinsertarCli.add(aNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(67, 495, 326, -1));

        jLabel14.setText("Domiciliado");
        jPinsertarCli.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 357, -1, -1));
        jPinsertarCli.add(ctDomiciliado, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 354, 70, -1));

        jLabel15.setText("Referencia Bancaria");
        jPinsertarCli.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 357, -1, -1));
        jPinsertarCli.add(ctRefBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 354, 93, -1));

        bNuevo.setBackground(new java.awt.Color(204, 255, 204));
        bNuevo.setText("Nuevo cliente");

        bModificar.setBackground(new java.awt.Color(255, 255, 153));
        bModificar.setText("Modificar cliente");

        bFormularioCon.setBackground(new java.awt.Color(204, 255, 255));
        bFormularioCon.setText("Formulario contactos");

        bImprime.setBackground(new java.awt.Color(102, 255, 102));
        bImprime.setText("Imprimir listado");

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableClientes);

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Ordenar listado por:");

        cbNombre.setForeground(new java.awt.Color(255, 255, 255));
        cbNombre.setText("Nombre");

        cbDescripcion.setForeground(new java.awt.Color(255, 255, 255));
        cbDescripcion.setText("Descripción");

        cbNif.setForeground(new java.awt.Color(255, 255, 255));
        cbNif.setText("NIF/CIF");

        jLabel17.setForeground(new java.awt.Color(255, 153, 153));
        jLabel17.setText("Pulse sobre la fila del cliente para ver todos sus datos.");

        javax.swing.GroupLayout bImprimirLayout = new javax.swing.GroupLayout(bImprimir);
        bImprimir.setLayout(bImprimirLayout);
        bImprimirLayout.setHorizontalGroup(
            bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bImprimirLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bFormularioCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bImprimirLayout.createSequentialGroup()
                        .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPinsertarCli, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addGap(51, 51, 51)
                .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bImprime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bImprimirLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addGap(26, 26, 26)
                            .addComponent(cbNombre)
                            .addGap(30, 30, 30)
                            .addComponent(cbDescripcion)
                            .addGap(29, 29, 29)
                            .addComponent(cbNif)))
                    .addComponent(jLabel17))
                .addContainerGap(259, Short.MAX_VALUE))
        );
        bImprimirLayout.setVerticalGroup(
            bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bImprimirLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bImprimirLayout.createSequentialGroup()
                        .addComponent(jPinsertarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bImprimirLayout.createSequentialGroup()
                        .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbNombre)
                            .addComponent(cbDescripcion)
                            .addComponent(cbNif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(bImprimirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bImprime, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(bFormularioCon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        PanelPestañasPrincipal.addTab("CLIENTES", bImprimir);

        javax.swing.GroupLayout jPgestionLayout = new javax.swing.GroupLayout(jPgestion);
        jPgestion.setLayout(jPgestionLayout);
        jPgestionLayout.setHorizontalGroup(
            jPgestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPgestionLayout.setVerticalGroup(
            jPgestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesContratos.addTab("GESTION", jPgestion);

        javax.swing.GroupLayout jPestudiosLayout = new javax.swing.GroupLayout(jPestudios);
        jPestudios.setLayout(jPestudiosLayout);
        jPestudiosLayout.setHorizontalGroup(
            jPestudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPestudiosLayout.setVerticalGroup(
            jPestudiosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesContratos.addTab("ESTUDIOS ACTIVOS", jPestudios);

        javax.swing.GroupLayout jPcontratosLayout = new javax.swing.GroupLayout(jPcontratos);
        jPcontratos.setLayout(jPcontratosLayout);
        jPcontratosLayout.setHorizontalGroup(
            jPcontratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesContratos)
        );
        jPcontratosLayout.setVerticalGroup(
            jPcontratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesContratos)
        );

        PanelPestañasPrincipal.addTab("CONTRATOS", jPcontratos);

        javax.swing.GroupLayout jPfacMensLayout = new javax.swing.GroupLayout(jPfacMens);
        jPfacMens.setLayout(jPfacMensLayout);
        jPfacMensLayout.setHorizontalGroup(
            jPfacMensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
        );
        jPfacMensLayout.setVerticalGroup(
            jPfacMensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );

        PanelPestañasPrincipal.addTab("FACTURACION MENSUAL", jPfacMens);

        javax.swing.GroupLayout jPfacExtraLayout = new javax.swing.GroupLayout(jPfacExtra);
        jPfacExtra.setLayout(jPfacExtraLayout);
        jPfacExtraLayout.setHorizontalGroup(
            jPfacExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
        );
        jPfacExtraLayout.setVerticalGroup(
            jPfacExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );

        PanelPestañasPrincipal.addTab("FACTURAS EXTRA", jPfacExtra);

        javax.swing.GroupLayout jPempleadosLayout = new javax.swing.GroupLayout(jPempleados);
        jPempleados.setLayout(jPempleadosLayout);
        jPempleadosLayout.setHorizontalGroup(
            jPempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1385, Short.MAX_VALUE)
        );
        jPempleadosLayout.setVerticalGroup(
            jPempleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );

        PanelPestañasPrincipal.addTab("EMPLEADOS", jPempleados);

        javax.swing.GroupLayout jPhistoricoLayout = new javax.swing.GroupLayout(jPhistorico);
        jPhistorico.setLayout(jPhistoricoLayout);
        jPhistoricoLayout.setHorizontalGroup(
            jPhistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPhistoricoLayout.setVerticalGroup(
            jPhistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesOtros.addTab("HISTORICO FACTURAS", jPhistorico);

        javax.swing.GroupLayout jPhojasBanLayout = new javax.swing.GroupLayout(jPhojasBan);
        jPhojasBan.setLayout(jPhojasBanLayout);
        jPhojasBanLayout.setHorizontalGroup(
            jPhojasBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPhojasBanLayout.setVerticalGroup(
            jPhojasBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesOtros.addTab("HOJAS BANCO", jPhojasBan);

        javax.swing.GroupLayout jPrecibosLayout = new javax.swing.GroupLayout(jPrecibos);
        jPrecibos.setLayout(jPrecibosLayout);
        jPrecibosLayout.setHorizontalGroup(
            jPrecibosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPrecibosLayout.setVerticalGroup(
            jPrecibosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesOtros.addTab("RECIBOS", jPrecibos);

        javax.swing.GroupLayout jPetiquetasLayout = new javax.swing.GroupLayout(jPetiquetas);
        jPetiquetas.setLayout(jPetiquetasLayout);
        jPetiquetasLayout.setHorizontalGroup(
            jPetiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPetiquetasLayout.setVerticalGroup(
            jPetiquetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesOtros.addTab("ETIQUETAS", jPetiquetas);

        javax.swing.GroupLayout jPotrosLayout = new javax.swing.GroupLayout(jPotros);
        jPotros.setLayout(jPotrosLayout);
        jPotrosLayout.setHorizontalGroup(
            jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesOtros)
        );
        jPotrosLayout.setVerticalGroup(
            jPotrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesOtros)
        );

        PanelPestañasPrincipal.addTab("OTROS", jPotros);

        javax.swing.GroupLayout jPcerrarLayout = new javax.swing.GroupLayout(jPcerrar);
        jPcerrar.setLayout(jPcerrarLayout);
        jPcerrarLayout.setHorizontalGroup(
            jPcerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPcerrarLayout.setVerticalGroup(
            jPcerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesPrograma.addTab("CERRAR PROGRAMA", jPcerrar);

        javax.swing.GroupLayout jPcontraseñaLayout = new javax.swing.GroupLayout(jPcontraseña);
        jPcontraseña.setLayout(jPcontraseñaLayout);
        jPcontraseñaLayout.setHorizontalGroup(
            jPcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPcontraseñaLayout.setVerticalGroup(
            jPcontraseñaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesPrograma.addTab("CAMBIAR CONTRASEÑA", jPcontraseña);

        javax.swing.GroupLayout jPipcLayout = new javax.swing.GroupLayout(jPipc);
        jPipc.setLayout(jPipcLayout);
        jPipcLayout.setHorizontalGroup(
            jPipcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPipcLayout.setVerticalGroup(
            jPipcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesPrograma.addTab("ACTUALIZAR IPC", jPipc);

        javax.swing.GroupLayout jPnumFacLayout = new javax.swing.GroupLayout(jPnumFac);
        jPnumFac.setLayout(jPnumFacLayout);
        jPnumFacLayout.setHorizontalGroup(
            jPnumFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPnumFacLayout.setVerticalGroup(
            jPnumFacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesPrograma.addTab("AJUSTAR NUMERO FACTURA", jPnumFac);

        javax.swing.GroupLayout jPcopiasSegLayout = new javax.swing.GroupLayout(jPcopiasSeg);
        jPcopiasSeg.setLayout(jPcopiasSegLayout);
        jPcopiasSegLayout.setHorizontalGroup(
            jPcopiasSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1380, Short.MAX_VALUE)
        );
        jPcopiasSegLayout.setVerticalGroup(
            jPcopiasSegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );

        PanelPesPrograma.addTab("COPIAS SEGURIDAD", jPcopiasSeg);

        javax.swing.GroupLayout jPprogramaLayout = new javax.swing.GroupLayout(jPprograma);
        jPprograma.setLayout(jPprogramaLayout);
        jPprogramaLayout.setHorizontalGroup(
            jPprogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesPrograma)
        );
        jPprogramaLayout.setVerticalGroup(
            jPprogramaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPesPrograma)
        );

        PanelPestañasPrincipal.addTab("PROGRAMA", jPprograma);

        javax.swing.GroupLayout PanelGUILayout = new javax.swing.GroupLayout(PanelGUI);
        PanelGUI.setLayout(PanelGUILayout);
        PanelGUILayout.setHorizontalGroup(
            PanelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPestañasPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        PanelGUILayout.setVerticalGroup(
            PanelGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPestañasPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 1202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGUI;
    private javax.swing.JTabbedPane PanelPesContratos;
    private javax.swing.JTabbedPane PanelPesOtros;
    private javax.swing.JTabbedPane PanelPesPrograma;
    private javax.swing.JTabbedPane PanelPestañasPrincipal;
    private javax.swing.JScrollPane aNotas;
    private javax.swing.JButton bFormularioCon;
    private javax.swing.JButton bImprime;
    private javax.swing.JPanel bImprimir;
    private javax.swing.JButton bModificar;
    private javax.swing.JButton bNuevo;
    private javax.swing.JCheckBox cbDescripcion;
    private javax.swing.JCheckBox cbNif;
    private javax.swing.JCheckBox cbNombre;
    private javax.swing.JTextField ctCliente;
    private javax.swing.JTextField ctContacto;
    private javax.swing.JTextField ctCp;
    private javax.swing.JTextField ctCuenta;
    private javax.swing.JTextField ctDescripcion;
    private javax.swing.JTextField ctDomiciliado;
    private javax.swing.JTextField ctDomicilio;
    private javax.swing.JTextField ctLocalidad;
    private javax.swing.JTextField ctNif;
    private javax.swing.JTextField ctNombre;
    private javax.swing.JTextField ctProvincia;
    private javax.swing.JTextField ctRefBan;
    private javax.swing.JTextField ctTlfCli;
    private javax.swing.JTextField ctTlfContacto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JPanel jPcerrar;
    private javax.swing.JPanel jPcontraseña;
    private javax.swing.JPanel jPcontratos;
    private javax.swing.JPanel jPcopiasSeg;
    private javax.swing.JPanel jPempleados;
    private javax.swing.JPanel jPestudios;
    private javax.swing.JPanel jPetiquetas;
    private javax.swing.JPanel jPfacExtra;
    private javax.swing.JPanel jPfacMens;
    private javax.swing.JPanel jPgestion;
    private javax.swing.JPanel jPhistorico;
    private javax.swing.JPanel jPhojasBan;
    private javax.swing.JPanel jPinicio;
    private javax.swing.JPanel jPinsertarCli;
    private javax.swing.JPanel jPipc;
    private javax.swing.JPanel jPnumFac;
    private javax.swing.JPanel jPotros;
    private javax.swing.JPanel jPprograma;
    private javax.swing.JPanel jPrecibos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
